# file: .github/dependabot.yml
# version: 1.1.0
# guid: 2a29e7e4-bad7-467f-9c24-f9006972a41a
# last-edited: 2026-07-16

version: 2

multi-ecosystem-groups:
  dependencies:
    schedule:
      interval: weekly
      day: tuesday
      time: "10:00"
      timezone: America/New_York
    labels:
      - dependencies
      - dependabot
    commit-message:
      prefix: deps
      include: scope

updates:
  # Docker
  - package-ecosystem: docker
    directory: /
    patterns: ["*"]
    multi-ecosystem-group: dependencies
    labels:
      - containers

  # Github Actions
  - package-ecosystem: github-actions
    directory: /
    patterns: ["*"]
    multi-ecosystem-group: dependencies
    labels:
      - github-actions
      - ci-cd

  # Gomod
  - package-ecosystem: gomod
    directory: /
    patterns: ["*"]
    multi-ecosystem-group: dependencies
    labels:
      - tech:go
